(function(){
  const HEALTH_KEY='ib_nyc_ops_store_health_v01';
  const OPS_KEY='ib_nyc_ops_procurement_visits_v01';
  const q=(s,r=document)=>r.querySelector(s);
  const qa=(s,r=document)=>[...r.querySelectorAll(s)];
  const safe=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const slug=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const today=()=>new Date().toISOString().slice(0,10);

  const healthSeed=[
    {id:'HLT-001',service:'Retail Pro POS — downstairs',status:'Operational',impact:'POS currently working downstairs.',owner:'Store / Italy IT',rootCause:'No current outage downstairs.',nextAction:'Monitor while network work continues.',evidence:'Karen status email · Sep 4, 2026',updated:'2026-09-04'},
    {id:'HLT-002',service:'Upstairs connectivity',status:'Degraded',impact:'Upstairs operations remain affected by unreliable Wi‑Fi/network coverage.',owner:'Dylan / eMazzanti / Pietro',rootCause:'Signal path / Wi‑Fi coverage suspected; final cause not yet confirmed.',nextAction:'Install rush Access Point after delivery, then validate upstairs coverage.',evidence:'Karen status email · Sep 4, 2026',updated:'2026-09-04'},
    {id:'HLT-003',service:'Store phones',status:'Under Investigation',impact:'Phone availability at store level may be affected.',owner:'Nirvan / Dylan',rootCause:'Unconfirmed. Internet/Wi‑Fi may be related, but phone service is separate.',nextAction:'Retest phones after network/AP work before declaring root cause.',evidence:'Karen status email · Sep 4, 2026',updated:'2026-09-04'},
    {id:'HLT-004',service:'Firewall administrative access',status:'Needs Confirmation',impact:'Technicians may be blocked from completing network work without authorized access.',owner:'Damiano / Italy IT',rootCause:'No onsite technician had confirmed firewall credentials during the visit.',nextAction:'Confirm authorized admin access exists in Pass/private vault before next visit.',evidence:'Karen email · Sep 3, 2026',updated:'2026-09-03'},
    {id:'HLT-005',service:'UPS power protection',status:'Missing',impact:'Critical PCs remain exposed to outages/surges until UPS units are installed.',owner:'Pietro / Store / Damiano',rootCause:'UPS units were not included / had not yet been purchased.',nextAction:'Purchase two UPS units and connect critical PCs.',evidence:'Nate + Damiano emails · Sep 2–3, 2026',updated:'2026-09-03'},
    {id:'HLT-006',service:'Spectrum internet',status:'Operational / Monitor',impact:'Primary store internet path.',owner:'Store / Spectrum / IT',rootCause:'No confirmed current ISP outage; continue monitoring during network stabilization.',nextAction:'Keep Spectrum as primary and validate support/escalation path.',evidence:'Current network baseline',updated:'2026-09-06'}
  ];

  const opsSeed={
    purchases:[
      {id:'PUR-001',item:'Access Point hardware',category:'Network / Wi‑Fi',qty:'1',status:'Rush Ordered',source:'eMazzanti / approved vendor',model:'Vendor-selected AP hardware',expected:'Sep 7–8, 2026',installOwner:'Dylan',projectId:'PRJ-0002',dependency:'Hardware delivery before onsite installation.',verification:'Validate upstairs Wi‑Fi, phone behavior and network stability after install.',risk:'Upstairs remains degraded until delivered/installed.',notes:'Invoice being signed to rush the order.',updated:'2026-09-04'},
      {id:'PUR-002',item:'UPS units for critical PCs',category:'Power Protection',qty:'2',status:'Not Purchased',source:'Local retail / Amazon / direct sourcing',model:'APC 660VA / 330W class recommended by RIS',expected:'TBD',installOwner:'Pietro / Store',projectId:'PRJ-0008',dependency:'Confirm the two critical PCs and outlet/load requirements.',verification:'Both PCs protected; power-loss/restart behavior tested.',risk:'Power interruption/surge exposure until installed.',notes:'RIS advised self-sourcing may be faster and less expensive.',updated:'2026-09-03'},
      {id:'PUR-003',item:'US-compatible power supply / adapter correction',category:'Workstation Hardware',qty:'As required',status:'Temporary Workaround',source:'Store / local replacement',model:'US-compatible power supply or approved universal adapter',expected:'Next hardware visit',installOwner:'Pietro / onsite support',projectId:'PRJ-0004',dependency:'Identify affected laptop/PC and confirm permanent power supply.',verification:'No workstation depends on a temporary incompatible power arrangement.',risk:'Temporary adapters should not become the undocumented permanent standard.',notes:'A shipped power supply was not suitable for USA power; temporary universal/spare adapters were used.',updated:'2026-09-03'}
    ],
    visits:[
      {id:'VIS-001',technician:'Dylan / network specialist',scope:'Install upstairs Access Point and validate network coverage.',status:'Pending Hardware',date:'Target Sep 7–8, 2026',requiredBefore:'AP delivered; firewall/network access confirmed; install scope confirmed.',projectId:'PRJ-0002',verify:'Upstairs Wi‑Fi, phones, POS connectivity and segmentation behavior.',followUp:'Store Manager confirms service before closeout.',updated:'2026-09-04'},
      {id:'VIS-002',technician:'Nirvan / Dylan',scope:'Investigate phone availability versus network/Wi‑Fi condition.',status:'In Progress',date:'As coordinated',requiredBefore:'Keep phone root cause separate from assumptions about Wi‑Fi.',projectId:'PRJ-0001',verify:'Phone service restored and actual cause documented.',followUp:'Retest after AP/network work if required.',updated:'2026-09-04'},
      {id:'VIS-003',technician:'Harvey / onsite hardware support',scope:'Complete approved hardware replacements and workstation updates.',status:'Follow-up',date:'Next approved onsite window',requiredBefore:'Confirm exact supported scope and US-compatible power components.',projectId:'PRJ-0004',verify:'Hardware inventory updated; workstations power on, remain stable and match target configuration.',followUp:'Record replaced hardware and close remaining exceptions.',updated:'2026-09-03'}
    ],
    invoices:[
      {id:'INV-001',vendor:'RIS / infrastructure vendors',description:'Second-half project invoice',status:'Pending / Bank Issue Corrected',amount:'TBD',projectId:'PRJ-0001',nextAction:'Receive/confirm invoice after Italian bank issue is cleared.',updated:'2026-09-04'},
      {id:'INV-002',vendor:'RIS / infrastructure vendors',description:'Final project bill',status:'Expected',amount:'TBD',projectId:'PRJ-0001',nextAction:'Reconcile remaining project costs and review final invoice when issued.',updated:'2026-09-04'}
    ]
  };

  const projectControlDefaults={
    'PRJ-0001':{blockers:'Final segmentation/hardware validation\nFirewall administrative access needs confirmation\nVPN/DNS validation from Italy',rootCause:'Do not assign a single root cause until network, phone and VPN/DNS work is validated.',credentialAccessStatus:'Firewall admin access: needs confirmation. Keep the secret only in Pass/private vault.',vendorVisits:'Dylan / network specialist — return onsite after required hardware/access is available.\nNirvan / Dylan — phone/network investigation.',costsInvoices:'Second-half vendor invoice pending/being corrected after Italian bank issue. Final bill expected after remaining costs are reconciled.',verificationCriteria:'WatchGuard confirmed as central gateway; segmentation validated; DHCP/reservations stable; VPN works from Italy; store confirms service.',procurementNotes:'Rush AP hardware in progress. Two UPS units still need purchase/installation.'},
    'PRJ-0002':{blockers:'Access Point delivery\nFinal installation window\nPost-install store verification',rootCause:'Upstairs signal/coverage is the leading hypothesis, but final root cause remains unconfirmed until post-install validation.',credentialAccessStatus:'Network/firewall access must be confirmed before onsite installation.',vendorVisits:'Dylan — install AP after delivery, then validate upstairs coverage and phone behavior.',costsInvoices:'AP rush order / vendor cost to be reconciled in final infrastructure billing.',verificationCriteria:'Reliable upstairs Wi‑Fi; phone behavior retested; no regression to downstairs POS/network; Store Manager verification.',procurementNotes:'Access Point rush ordered; expected Monday/Tuesday per Sep 4 status.'},
    'PRJ-0003':{blockers:'Prism hostname resolution\nVPN route validation\nItaly-side retest',rootCause:'DNS/VPN dependency is the current investigation area, not yet a closed root cause.',credentialAccessStatus:'Remote/VPN credentials remain IT-controlled; do not place secrets in the project.',vendorVisits:'Remote validation by Damiano / Italy IT; Retail Pro escalation if application issue remains after network validation.',costsInvoices:'No application-specific cost confirmed in current baseline.',verificationCriteria:'Prism resolves correctly; port 8081 works; local store access and Italy remote access both pass.',procurementNotes:'No purchase should be made until DNS/VPN ownership is validated.'},
    'PRJ-0004':{blockers:'Physical inventory incomplete\nSome hardware roles/serials unknown\nUS power-supply compatibility exception',rootCause:'Legacy hardware and incomplete documentation create support uncertainty.',credentialAccessStatus:'Record credential location/owner only; secrets remain in Pass/private vault.',vendorVisits:'Harvey / onsite support — approved hardware replacements and workstation updates.',costsInvoices:'Track hardware replacement charges and final infrastructure invoice references.',verificationCriteria:'Current-state asset list complete; power supplies US-compatible; network map matches physical store state.',procurementNotes:'Permanent US-compatible power components should replace temporary adapters where required.'},
    'PRJ-0008':{blockers:'Two UPS units not purchased\nFinal critical-device load not documented',rootCause:'Power protection gap is confirmed; UPS sizing still requires the actual protected load.',credentialAccessStatus:'No password issue; keep mini-PC/service accounts in Pass once created.',vendorVisits:'Simple plug-in installation can be done by store/Pietro; technical validation required for automation node recovery behavior.',costsInvoices:'UPS purchase cost TBD; source locally or online based on speed/value.',verificationCriteria:'Critical PCs protected; correct load/runtime; clean restart or shutdown behavior tested; equipment labeled.',procurementNotes:'RIS recommends APC 660VA / 330W class. Confirm actual load before finalizing broader automation-node UPS sizing.'}
  };

  document.addEventListener('DOMContentLoaded',()=>waitForCore().then(init).catch(console.error));
  function waitForCore(){return new Promise((resolve,reject)=>{let n=0;const t=setInterval(()=>{if(typeof App!=='undefined'&&App.data&&typeof renderPage==='function'&&typeof renderNav==='function'){clearInterval(t);resolve()}else if(++n>180){clearInterval(t);reject(new Error('Operations control could not initialize'))}},50)})}

  function readHealth(){try{const v=JSON.parse(localStorage.getItem(HEALTH_KEY)||'null');if(Array.isArray(v))return v}catch(e){}localStorage.setItem(HEALTH_KEY,JSON.stringify(healthSeed));return JSON.parse(JSON.stringify(healthSeed))}
  function saveHealth(rows){localStorage.setItem(HEALTH_KEY,JSON.stringify(rows))}
  function readOps(){try{const v=JSON.parse(localStorage.getItem(OPS_KEY)||'null');if(v&&Array.isArray(v.purchases)&&Array.isArray(v.visits)&&Array.isArray(v.invoices))return v}catch(e){}localStorage.setItem(OPS_KEY,JSON.stringify(opsSeed));return JSON.parse(JSON.stringify(opsSeed))}
  function saveOps(v){localStorage.setItem(OPS_KEY,JSON.stringify(v))}
  function canEdit(){const s=window.IBAuth?.current?.();const role=s?.user?.role||App.role;return ['project_manager','it_admin'].includes(role)}

  function init(){
    addNav();
    const previous=renderPage;
    renderPage=function(){
      const root=q('#pageRoot');
      if(App.page==='store_health')return renderHealth(root);
      if(App.page==='purchases_visits')return renderPurchases(root);
      previous();
      if(App.page==='dashboard')injectHealthStrip();
    };
    wrapProjectWorkspace();
    renderNav();if(typeof render==='function')render();
  }

  function addNav(){
    const defs={
      store_manager:[['store_health','♥','Store Health']],
      project_manager:[['store_health','♥','Store Health'],['purchases_visits','$','Purchases & Visits']],
      management:[['store_health','♥','Store Health'],['purchases_visits','$','Purchases & Visits']],
      it_admin:[['store_health','♥','Store Health'],['purchases_visits','$','Purchases & Visits']]
    };
    Object.entries(defs).forEach(([role,items])=>{const list=App.nav[role];if(!list)return;items.forEach((item,idx)=>{if(list.some(x=>x[0]===item[0]))return;const dashboard=list.findIndex(x=>x[0]==='dashboard');list.splice(Math.max(0,dashboard+1+idx),0,item)})});
  }

  function statusTone(status){const s=String(status||'').toLowerCase();if(s.includes('operational')&&!s.includes('monitor'))return 'ok';if(s.includes('degraded')||s.includes('missing')||s.includes('blocked'))return 'bad';if(s.includes('investigation')||s.includes('confirmation')||s.includes('monitor')||s.includes('pending'))return 'warn';return 'neutral'}
  function healthSummary(){const rows=readHealth();return {rows,bad:rows.filter(x=>statusTone(x.status)==='bad').length,warn:rows.filter(x=>statusTone(x.status)==='warn').length,ok:rows.filter(x=>statusTone(x.status)==='ok').length}}

  function injectHealthStrip(){
    const root=q('#pageRoot');if(!root||q('.oc-health-strip',root))return;const s=healthSummary();const head=q('.page-head',root);if(!head)return;
    const wrap=document.createElement('section');wrap.className='oc-health-strip';wrap.innerHTML=`<div class="oc-health-head"><div><span class="eyebrow">STORE OPERATING STATUS</span><strong>${s.bad?'Attention required':s.warn?'Operating with open validations':'Operational'}</strong></div><button class="btn" id="ocOpenHealth">Open Store Health</button></div><div class="oc-health-chips">${s.rows.map(x=>`<span class="oc-health-chip ${statusTone(x.status)}"><i></i>${safe(x.service)} <b>${safe(x.status)}</b></span>`).join('')}</div>`;
    head.insertAdjacentElement('afterend',wrap);q('#ocOpenHealth',wrap).onclick=()=>{App.page='store_health';render()};
  }

  function renderHealth(root){
    const rows=readHealth(),edit=canEdit(),s=healthSummary();
    root.innerHTML=`${pageHead('Store Health','One operational picture of what is working, degraded, under investigation or still exposed.','NYC STORE STATUS')}<div class="oc-kpis"><div><strong>${s.ok}</strong><span>Operational</span></div><div><strong>${s.warn}</strong><span>Needs validation</span></div><div><strong>${s.bad}</strong><span>Active risk / degraded</span></div><div><strong>${rows.length}</strong><span>Services tracked</span></div></div><div class="panel oc-health-panel"><div class="panel-head"><div><h3>Current Operating Status</h3><p class="muted">Root cause stays “unconfirmed” until the responsible owner validates it.</p></div>${edit?'<button class="btn primary" id="ocAddHealth">+ Add service</button>':''}</div><div class="oc-health-grid">${rows.map(h=>healthCard(h)).join('')}</div></div><div class="baseline-note" style="margin-top:16px"><strong>Control rule:</strong> a vendor visit or email does not automatically mean an issue is resolved. Close a service only after the responsible owner and store verification confirm the outcome.</div>`;
    qa('[data-health-id]',root).forEach(c=>c.onclick=()=>openHealth(c.dataset.healthId));q('#ocAddHealth')?.addEventListener('click',()=>openHealth('new'));
  }
  function healthCard(h){return `<article class="oc-health-card ${statusTone(h.status)}" data-health-id="${safe(h.id)}"><div class="oc-card-top"><span class="oc-status-dot"></span><span class="oc-status">${safe(h.status)}</span><span class="oc-date">${safe(h.updated||'')}</span></div><h3>${safe(h.service)}</h3><p>${safe(h.impact)}</p><dl><div><dt>Owner</dt><dd>${safe(h.owner)}</dd></div><div><dt>Root cause</dt><dd>${safe(h.rootCause)}</dd></div><div><dt>Next action</dt><dd>${safe(h.nextAction)}</dd></div></dl><span class="oc-evidence">${safe(h.evidence||'')}</span></article>`}

  function openHealth(id){
    const rows=readHealth(),existing=rows.find(x=>x.id===id),edit=canEdit();const h=existing||{id:`HLT-${String(rows.length+1).padStart(3,'0')}`,service:'',status:'Needs Confirmation',impact:'',owner:'',rootCause:'Unconfirmed',nextAction:'',evidence:'',updated:today()};
    q('#modalRoot').innerHTML=`<div class="oc-modal-backdrop" id="ocModal"><div class="oc-modal"><header><div><span class="eyebrow">STORE HEALTH</span><h2>${safe(existing?h.service:'New service')}</h2></div><button class="pw-close" id="ocClose">×</button></header><div class="oc-form"><label class="full">Service<input name="service" value="${safe(h.service)}" ${edit?'':'disabled'}></label><label>Status<select name="status" ${edit?'':'disabled'}>${['Operational','Operational / Monitor','Degraded','Under Investigation','Needs Confirmation','Missing','Planned','Resolved'].map(v=>`<option ${v===h.status?'selected':''}>${safe(v)}</option>`).join('')}</select></label><label>Owner<input name="owner" value="${safe(h.owner)}" ${edit?'':'disabled'}></label><label class="full">Impact<textarea name="impact" ${edit?'':'disabled'}>${safe(h.impact)}</textarea></label><label class="full">Root cause / current hypothesis<textarea name="rootCause" ${edit?'':'disabled'}>${safe(h.rootCause)}</textarea></label><label class="full">Next action<textarea name="nextAction" ${edit?'':'disabled'}>${safe(h.nextAction)}</textarea></label><label>Evidence / source<input name="evidence" value="${safe(h.evidence)}" ${edit?'':'disabled'}></label><label>Last updated<input name="updated" type="date" value="${safe(h.updated)}" ${edit?'':'disabled'}></label></div><footer>${edit?'<button class="btn primary" id="ocSaveHealth">Save status</button>':'<span class="muted">View only</span>'}</footer></div></div>`;
    q('#ocClose').onclick=()=>q('#ocModal')?.remove();q('#ocModal').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.remove()};
    q('#ocSaveHealth')?.addEventListener('click',()=>{const patch={};qa('[name]',q('#ocModal')).forEach(x=>patch[x.name]=x.value);const row={...h,...patch};const i=rows.findIndex(x=>x.id===row.id);if(i>=0)rows[i]=row;else rows.push(row);saveHealth(rows);q('#ocModal').remove();render();if(typeof toast==='function')toast('Store health updated')});
  }

  function renderPurchases(root){
    const data=readOps(),edit=canEdit();
    root.innerHTML=`${pageHead('Purchases & Visits','Track what must be bought, what is waiting on delivery, who is returning onsite and what must be verified.','OPERATIONS CONTROL')}<div class="oc-kpis"><div><strong>${data.purchases.filter(x=>!['Installed','Completed'].includes(x.status)).length}</strong><span>Open purchases</span></div><div><strong>${data.visits.filter(x=>!['Completed','Closed'].includes(x.status)).length}</strong><span>Visits / follow-ups</span></div><div><strong>${data.invoices.filter(x=>!['Paid','Closed'].includes(x.status)).length}</strong><span>Commercial follow-ups</span></div><div><strong>${data.purchases.filter(x=>String(x.status).includes('Not Purchased')).length}</strong><span>Not yet purchased</span></div></div>
      <section class="panel oc-section"><div class="panel-head"><div><h3>Procurement & Installation</h3><p class="muted">Requested → approved → ordered → delivered → installed → verified.</p></div>${edit?'<button class="btn primary" id="ocAddPurchase">+ Add purchase</button>':''}</div><div class="oc-records">${data.purchases.map(p=>purchaseCard(p)).join('')}</div></section>
      <section class="panel oc-section"><div class="panel-head"><div><h3>Vendor Visits & Work Orders</h3><p class="muted">Every visit has prerequisites, scope and closeout criteria.</p></div>${edit?'<button class="btn primary" id="ocAddVisit">+ Add visit</button>':''}</div><div class="oc-records">${data.visits.map(v=>visitCard(v)).join('')}</div></section>
      <section class="panel oc-section"><div class="panel-head"><div><h3>Costs & Invoice Follow-up</h3><p class="muted">Operational visibility only — not accounting.</p></div>${edit?'<button class="btn" id="ocAddInvoice">+ Add invoice</button>':''}</div><div class="oc-records compact">${data.invoices.map(i=>invoiceCard(i)).join('')}</div></section>`;
    qa('[data-purchase-id]',root).forEach(x=>x.onclick=()=>openRecord('purchase',x.dataset.purchaseId));qa('[data-visit-id]',root).forEach(x=>x.onclick=()=>openRecord('visit',x.dataset.visitId));qa('[data-invoice-id]',root).forEach(x=>x.onclick=()=>openRecord('invoice',x.dataset.invoiceId));q('#ocAddPurchase')?.addEventListener('click',()=>openRecord('purchase','new'));q('#ocAddVisit')?.addEventListener('click',()=>openRecord('visit','new'));q('#ocAddInvoice')?.addEventListener('click',()=>openRecord('invoice','new'));
  }
  function purchaseCard(p){return `<article class="oc-record" data-purchase-id="${safe(p.id)}"><div class="oc-record-top"><span>${safe(p.id)} · ${safe(p.category)}</span><b class="pill ${slug(p.status)}">${safe(p.status)}</b></div><h3>${safe(p.item)}</h3><p>${safe(p.model||'')}</p><div class="oc-record-grid"><span><b>Qty</b>${safe(p.qty)}</span><span><b>Source</b>${safe(p.source)}</span><span><b>Expected</b>${safe(p.expected)}</span><span><b>Install owner</b>${safe(p.installOwner)}</span></div><div class="oc-record-next"><b>Verification:</b> ${safe(p.verification)}</div></article>`}
  function visitCard(v){return `<article class="oc-record" data-visit-id="${safe(v.id)}"><div class="oc-record-top"><span>${safe(v.id)} · ${safe(v.date)}</span><b class="pill ${slug(v.status)}">${safe(v.status)}</b></div><h3>${safe(v.technician)}</h3><p>${safe(v.scope)}</p><div class="oc-record-next"><b>Required before visit:</b> ${safe(v.requiredBefore)}</div><div class="oc-record-next"><b>Closeout:</b> ${safe(v.verify)}</div></article>`}
  function invoiceCard(i){return `<article class="oc-record" data-invoice-id="${safe(i.id)}"><div class="oc-record-top"><span>${safe(i.id)} · ${safe(i.vendor)}</span><b class="pill ${slug(i.status)}">${safe(i.status)}</b></div><h3>${safe(i.description)}</h3><div class="oc-record-grid"><span><b>Amount</b>${safe(i.amount)}</span><span><b>Project</b>${safe(i.projectId)}</span></div><div class="oc-record-next"><b>Next:</b> ${safe(i.nextAction)}</div></article>`}

  function openRecord(type,id){
    const data=readOps(),edit=canEdit();const key=type==='purchase'?'purchases':type==='visit'?'visits':'invoices';let row=data[key].find(x=>x.id===id);
    if(!row){row=type==='purchase'?{id:`PUR-${String(data.purchases.length+1).padStart(3,'0')}`,item:'',category:'',qty:'1',status:'Requested',source:'',model:'',expected:'TBD',installOwner:'',projectId:'',dependency:'',verification:'',risk:'',notes:'',updated:today()}:type==='visit'?{id:`VIS-${String(data.visits.length+1).padStart(3,'0')}`,technician:'',scope:'',status:'Planned',date:'TBD',requiredBefore:'',projectId:'',verify:'',followUp:'',updated:today()}:{id:`INV-${String(data.invoices.length+1).padStart(3,'0')}`,vendor:'',description:'',status:'Expected',amount:'TBD',projectId:'',nextAction:'',updated:today()}}
    const fields=type==='purchase'?[['item','Item'],['category','Category'],['qty','Quantity'],['status','Status'],['source','Source / vendor'],['model','Model / specification'],['expected','Expected / target'],['installOwner','Install owner'],['projectId','Linked project'],['dependency','Dependency'],['verification','Verification criteria'],['risk','Risk if delayed'],['notes','Notes']]:type==='visit'?[['technician','Technician / vendor'],['scope','Scope'],['status','Status'],['date','Date / target'],['requiredBefore','Required before visit'],['projectId','Linked project'],['verify','Verification / closeout'],['followUp','Follow-up']]:[['vendor','Vendor'],['description','Description'],['status','Status'],['amount','Amount'],['projectId','Linked project'],['nextAction','Next action']];
    q('#modalRoot').innerHTML=`<div class="oc-modal-backdrop" id="ocModal"><div class="oc-modal"><header><div><span class="eyebrow">${safe(type.toUpperCase())}</span><h2>${safe(row.item||row.technician||row.description||'New record')}</h2></div><button class="pw-close" id="ocClose">×</button></header><div class="oc-form">${fields.map(([name,label],idx)=>`<label class="${['scope','requiredBefore','verify','followUp','dependency','verification','risk','notes','nextAction'].includes(name)?'full':''}">${safe(label)}${['scope','requiredBefore','verify','followUp','dependency','verification','risk','notes','nextAction'].includes(name)?`<textarea name="${name}" ${edit?'':'disabled'}>${safe(row[name]||'')}</textarea>`:`<input name="${name}" value="${safe(row[name]||'')}" ${edit?'':'disabled'}>`}</label>`).join('')}</div><footer>${edit?'<button class="btn primary" id="ocSaveRecord">Save record</button>':'<span class="muted">View only</span>'}</footer></div></div>`;
    q('#ocClose').onclick=()=>q('#ocModal')?.remove();q('#ocModal').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.remove()};q('#ocSaveRecord')?.addEventListener('click',()=>{const patch={};qa('[name]',q('#ocModal')).forEach(x=>patch[x.name]=x.value);const updated={...row,...patch,updated:today()};const i=data[key].findIndex(x=>x.id===updated.id);if(i>=0)data[key][i]=updated;else data[key].push(updated);saveOps(data);q('#ocModal').remove();render();if(typeof toast==='function')toast('Operations record saved')});
  }

  function wrapProjectWorkspace(){
    let tries=0;const t=setInterval(()=>{tries++;if(window.IBProjectWorkspace?.open){clearInterval(t);const original=window.IBProjectWorkspace.open;window.IBProjectWorkspace.open=async function(id){await original(id);injectProjectControl(id)};return}if(tries>120)clearInterval(t)},50)
  }
  function injectProjectControl(id){
    const tabs=q('.pw-tabs'),body=q('.pw-body'),p=App.data.projects.find(x=>x.id===id);if(!tabs||!body||!p||q('[data-pw-tab="control"]',tabs))return;
    const d=projectControlDefaults[id]||{};const values={blockers:p.blockers??d.blockers??'',rootCause:p.rootCause??d.rootCause??'',credentialAccessStatus:p.credentialAccessStatus??d.credentialAccessStatus??'',vendorVisits:p.vendorVisits??d.vendorVisits??'',costsInvoices:p.costsInvoices??d.costsInvoices??'',verificationCriteria:p.verificationCriteria??d.verificationCriteria??'',procurementNotes:p.procurementNotes??d.procurementNotes??''};const edit=canEdit();
    const tab=document.createElement('button');tab.className='pw-tab';tab.dataset.pwTab='control';tab.textContent='Control';tabs.insertBefore(tab,q('[data-pw-tab="notes"]',tabs)||null);
    const panel=document.createElement('section');panel.className='pw-panel';panel.dataset.pwPanel='control';panel.innerHTML=`<div class="pw-note">Use this tab for operational control: blockers, access prerequisites, vendor visits, procurement, costs and verification. Never place raw passwords here.</div><div class="pw-section"><div class="pw-section-head"><div><h3>Blockers & Root Cause</h3><p>Keep assumptions separate from confirmed causes.</p></div></div><div class="pw-grid">${pwArea('Blockers','blockers',values.blockers,edit,'full tall')}${pwArea('Root cause / current hypothesis','rootCause',values.rootCause,edit,'full')}</div></div><div class="pw-section"><div class="pw-section-head"><div><h3>Access & Vendor Work</h3><p>Know what a technician needs before arriving onsite.</p></div></div><div class="pw-grid">${pwArea('Credential / access status','credentialAccessStatus',values.credentialAccessStatus,edit,'full')}${pwArea('Vendor visits / work orders','vendorVisits',values.vendorVisits,edit,'full tall')}</div></div><div class="pw-section"><div class="pw-section-head"><div><h3>Purchases, Costs & Closeout</h3></div></div><div class="pw-grid">${pwArea('Procurement notes','procurementNotes',values.procurementNotes,edit,'full')}${pwArea('Costs & invoices','costsInvoices',values.costsInvoices,edit,'full')}${pwArea('Verification / closeout criteria','verificationCriteria',values.verificationCriteria,edit,'full tall')}</div></div>`;
    body.insertBefore(panel,q('[data-pw-panel="notes"]',body)||null);
    tab.onclick=()=>{qa('.pw-tab').forEach(x=>x.classList.toggle('active',x===tab));qa('.pw-panel').forEach(x=>x.classList.toggle('active',x===panel))};
    qa('textarea,input,select',panel).forEach(x=>x.addEventListener('input',()=>{const u=q('#pwUnsaved');if(u)u.textContent='Unsaved changes'}));
  }
  function pwArea(label,name,value,edit,extra=''){return `<div class="pw-field ${extra}"><span>${safe(label)}</span>${edit?`<textarea class="pw-textarea ${extra.includes('tall')?'tall':''}" name="${name}">${safe(value)}</textarea>`:`<div class="pw-readonly">${safe(value||'—').replace(/\n/g,'<br>')}</div>`}</div>`}
})();
